# Generated by Django 2.2.7 on 2020-04-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_notifications', '0005_actionnotification_do_not_send_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionnotificationpreference',
            name='email_notification_frequency',
            field=models.CharField(choices=[('* * * * *', 'Immediately'), ('*/30 * * * *', 'Every 30 minutes'), ('@daily', 'Daily')], default='@daily', max_length=64),
        ),
        migrations.AlterField(
            model_name='actionnotificationpreference',
            name='use_user_preference',
            field=models.BooleanField(default=False, help_text='Setting this true will cause frequency and is_email_separately to be ignored'),
        ),
    ]
