# Generated by Django 2.2.28 on 2022-05-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_notifications', '0006_auto_20200416_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionnotificationpreference',
            name='follow_topic',
            field=models.CharField(blank=True, default='', help_text='If a topic is set, only follow relationships with that topic are selected', max_length=255),
        ),
    ]
